\begin{frame}{Les pronoms dans les langues\Logo}
  \begin{enumerate}
    \item Les identités ethniques des locuteurs.trices prédisent le nom de la variété \smallcite{\parencite{klingler_language_2003}}
    \item Les pronoms peuvent différencier le français et le créole structurellement (\lexi{je} vs \lexi{mo}) \smallcite{\parencite{klingler_probleme_2005}}
    \item Le pronom \lexi{elle} au lieu de \lexi{li} (f.) est plus fréquent pour les Blanc.he.s \smallcite{\parencite{klingler_if_2003}}
    \item[] (ou peut-être non \smallcite{\parencite{mayeux_rethinking_2019}})
    \item Moins de \lexi{ça} (3pl) avant les modaux \smallcite{\parencite{brown_pronominal_1988}}
  \end{enumerate}
\end{frame}